num_final_runs: 5
model_type: RNN_struct
train_epochs: 9
hp_epochs: 10
minib: 2000
batch_size_boosting: True
batch_size_steps: 3
cv_folds: 3
hp_dir: 'hyperparameters'
result_dir: 'results'
model_dir: 'models'
num_calibrations: 5
recalibrate: False
summary_only: False
